import {
  HistologicalGrade,
  Laterality,
  PairedLaterality,
  Sequence,
} from "../../generated/prisma/enums.ts";
import {
  inEnum,
  isDate,
  isSmallInt,
  isString,
  makeValidator,
  maxLen,
  trim,
} from "./common.ts";

export const createPathologyValidator = makeValidator({
  longestSymptomDurationMonths: [isSmallInt("must be a whole number")],
  anatomicalSite: [isString(), trim(), maxLen(128)],
  pathologySlideNo: [isString(), trim(), maxLen(64)],
  primaryTumorSite: [isString(), trim(), maxLen(128)],
  morphology: [isString(), trim(), maxLen(128)],
  icdoTopography: [isString(), trim(), maxLen(64)],
  topographySite: [isString(), trim(), maxLen(128)],
  icdoMorphology: [isString(), trim(), maxLen(64)],
  histologyMorphology: [isString(), trim(), maxLen(128)],
  morphologyGrade: [inEnum(HistologicalGrade)],
  secondarySite: [isString(), trim(), maxLen(128)],
  secondarySiteCode: [isString(), trim(), maxLen(64)],
  metastasisMorphology: [isString(), trim(), maxLen(128)],
  metastasisMorphologyCode: [isString(), trim(), maxLen(64)],
  metastasisMorphologyGrade: [inEnum(HistologicalGrade)],
  icd10Site: [isString(), trim(), maxLen(64)],
  laterality: [inEnum(Laterality)],
  pairedLaterality: [inEnum(PairedLaterality)],
  sequence: [inEnum(Sequence)],
  pathologyDateOfReporting: [isDate()],
});

export const updatePathologyValidator = makeValidator({
  longestSymptomDurationMonths: [isSmallInt("must be a whole number")],
  anatomicalSite: [isString(), trim(), maxLen(128)],
  pathologySlideNo: [isString(), trim(), maxLen(64)],
  primaryTumorSite: [isString(), trim(), maxLen(128)],
  morphology: [isString(), trim(), maxLen(128)],
  icdoTopography: [isString(), trim(), maxLen(64)],
  topographySite: [isString(), trim(), maxLen(128)],
  icdoMorphology: [isString(), trim(), maxLen(64)],
  histologyMorphology: [isString(), trim(), maxLen(128)],
  morphologyGrade: [inEnum(HistologicalGrade)],
  secondarySite: [isString(), trim(), maxLen(128)],
  secondarySiteCode: [isString(), trim(), maxLen(64)],
  metastasisMorphology: [isString(), trim(), maxLen(128)],
  metastasisMorphologyCode: [isString(), trim(), maxLen(64)],
  metastasisMorphologyGrade: [inEnum(HistologicalGrade)],
  icd10Site: [isString(), trim(), maxLen(64)],
  laterality: [inEnum(Laterality)],
  pairedLaterality: [inEnum(PairedLaterality)],
  sequence: [inEnum(Sequence)],
  pathologyDateOfReporting: [isDate()],
});
